version: "3.8"
services:
  localstack:
    image: localstack/localstack:2.2
    platform: linux/arm64/v8
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ec2,lambda,sts,iam,rds,route53
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./localstack-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
